/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICrossDomainMessenger } from "./ICrossDomainMessenger";
export type { SimpleStorage } from "./SimpleStorage";
