/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IOVM_L1ERC721Gateway } from "./IOVM_L1ERC721Gateway";
export type { IOVM_L2DepositedERC721 } from "./IOVM_L2DepositedERC721";
