/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface Abs_L1ERC721GatewayInterface extends utils.Interface {
  functions: {
    "DEFAULT_FINALIZE_DEPOSIT_GAS()": FunctionFragment;
    "deposit(uint256)": FunctionFragment;
    "depositTo(address,uint256)": FunctionFragment;
    "depositedToken()": FunctionFragment;
    "finalizeWithdrawal(address,uint256)": FunctionFragment;
    "getFinalizeDepositGas()": FunctionFragment;
    "messenger()": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "originalToken()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DEFAULT_FINALIZE_DEPOSIT_GAS"
      | "deposit"
      | "depositTo"
      | "depositedToken"
      | "finalizeWithdrawal"
      | "getFinalizeDepositGas"
      | "messenger"
      | "onERC721Received"
      | "originalToken"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_FINALIZE_DEPOSIT_GAS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "depositTo",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "depositedToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeWithdrawal",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFinalizeDepositGas",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "messenger", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "originalToken",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_FINALIZE_DEPOSIT_GAS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "depositTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFinalizeDepositGas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "messenger", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "originalToken",
    data: BytesLike
  ): Result;

  events: {
    "DepositInitiated(address,address,uint256)": EventFragment;
    "WithdrawalFinalized(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DepositInitiated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawalFinalized"): EventFragment;
}

export interface DepositInitiatedEventObject {
  _from: string;
  _to: string;
  _tokenId: BigNumber;
}
export type DepositInitiatedEvent = TypedEvent<
  [string, string, BigNumber],
  DepositInitiatedEventObject
>;

export type DepositInitiatedEventFilter =
  TypedEventFilter<DepositInitiatedEvent>;

export interface WithdrawalFinalizedEventObject {
  _to: string;
  _tokenId: BigNumber;
}
export type WithdrawalFinalizedEvent = TypedEvent<
  [string, BigNumber],
  WithdrawalFinalizedEventObject
>;

export type WithdrawalFinalizedEventFilter =
  TypedEventFilter<WithdrawalFinalizedEvent>;

export interface Abs_L1ERC721Gateway extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: Abs_L1ERC721GatewayInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DEFAULT_FINALIZE_DEPOSIT_GAS(overrides?: CallOverrides): Promise<[number]>;

    deposit(
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositTo(
      _to: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositedToken(overrides?: CallOverrides): Promise<[string]>;

    finalizeWithdrawal(
      _to: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getFinalizeDepositGas(overrides?: CallOverrides): Promise<[number]>;

    messenger(overrides?: CallOverrides): Promise<[string]>;

    onERC721Received(
      _operator: PromiseOrValue<string>,
      _from: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    originalToken(overrides?: CallOverrides): Promise<[string]>;
  };

  DEFAULT_FINALIZE_DEPOSIT_GAS(overrides?: CallOverrides): Promise<number>;

  deposit(
    _tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositTo(
    _to: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositedToken(overrides?: CallOverrides): Promise<string>;

  finalizeWithdrawal(
    _to: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getFinalizeDepositGas(overrides?: CallOverrides): Promise<number>;

  messenger(overrides?: CallOverrides): Promise<string>;

  onERC721Received(
    _operator: PromiseOrValue<string>,
    _from: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    _data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  originalToken(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    DEFAULT_FINALIZE_DEPOSIT_GAS(overrides?: CallOverrides): Promise<number>;

    deposit(
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    depositTo(
      _to: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    depositedToken(overrides?: CallOverrides): Promise<string>;

    finalizeWithdrawal(
      _to: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getFinalizeDepositGas(overrides?: CallOverrides): Promise<number>;

    messenger(overrides?: CallOverrides): Promise<string>;

    onERC721Received(
      _operator: PromiseOrValue<string>,
      _from: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    originalToken(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "DepositInitiated(address,address,uint256)"(
      _from?: PromiseOrValue<string> | null,
      _to?: null,
      _tokenId?: null
    ): DepositInitiatedEventFilter;
    DepositInitiated(
      _from?: PromiseOrValue<string> | null,
      _to?: null,
      _tokenId?: null
    ): DepositInitiatedEventFilter;

    "WithdrawalFinalized(address,uint256)"(
      _to?: PromiseOrValue<string> | null,
      _tokenId?: null
    ): WithdrawalFinalizedEventFilter;
    WithdrawalFinalized(
      _to?: PromiseOrValue<string> | null,
      _tokenId?: null
    ): WithdrawalFinalizedEventFilter;
  };

  estimateGas: {
    DEFAULT_FINALIZE_DEPOSIT_GAS(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositTo(
      _to: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositedToken(overrides?: CallOverrides): Promise<BigNumber>;

    finalizeWithdrawal(
      _to: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getFinalizeDepositGas(overrides?: CallOverrides): Promise<BigNumber>;

    messenger(overrides?: CallOverrides): Promise<BigNumber>;

    onERC721Received(
      _operator: PromiseOrValue<string>,
      _from: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    originalToken(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_FINALIZE_DEPOSIT_GAS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deposit(
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositTo(
      _to: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositedToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    finalizeWithdrawal(
      _to: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getFinalizeDepositGas(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    messenger(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onERC721Received(
      _operator: PromiseOrValue<string>,
      _from: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    originalToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
