/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { IERC20 } from "./IERC20";
export type { IERC20Metadata } from "./IERC20Metadata";
export type { L1CustomERC20 } from "./L1CustomERC20";
export type { OptimismUselessToken } from "./OptimismUselessToken";
