/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as libraries from "./libraries";
export type { libraries };
import type * as standards from "./standards";
export type { standards };
