/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICrossDomainMessenger__factory } from "./ICrossDomainMessenger__factory";
export { SimpleStorage__factory } from "./SimpleStorage__factory";
