/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ovm from "./OVM";
export type { ovm };
import type * as iOvm from "./iOVM";
export type { iOvm };
import type * as libraries from "./libraries";
export type { libraries };
export type { ExampleToken } from "./ExampleToken";
