/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IOVM_L1ERC721Gateway__factory } from "./IOVM_L1ERC721Gateway__factory";
export { IOVM_L2DepositedERC721__factory } from "./IOVM_L2DepositedERC721__factory";
